import { AppThemeProvider } from "@/components";
import { geistMono, geistSans } from "@/fonts";
import "@/css/globals.css";

import type { ReactNode } from "react";
import type { Metadata } from "next";
import type { IRSC } from "@/types";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<IRSC>): ReactNode {
  // Fonts Variable, only reason for this to exist is to make syntax readable
  const fonts = `${geistSans.variable} ${geistMono.variable}`;

  return (
    <html lang="en">
      <body className={`${fonts} antialiased`}>
        <AppThemeProvider>{children}</AppThemeProvider>
      </body>
    </html>
  );
}
